### ISSUE TITLE
Integrated API and visualization dashboard for multiple wearable devices

### ISSUE THREAD

**Issue by pknmax** [arpanghosh8453/public-fitbit-projects#11]
Any plan to develop integrated API to get data from multiple wearable devices and then develop visualization dashboard?
Do you know any such already existing project?

**Comment by arpanghosh8453** [comment]
This project is designed for single-person use only. If you have multiple devices all linked to you, you can run separate instances, add data in a separate influxdB database, and use Grafana to create two separate dashboards for separate devices. I feel I do not understand your use-case here properly.

**Comment by pknmax** [comment]
something like this https://thryve.health/clinical-trial-solution/
is there any open-source solution available like this?

**Comment by arpanghosh8453** [comment]
There is no such option out there in my knowledge. This project is for fitbit-influxdb-grafana integration only. The other companies (i.e. Garmin) do not provide open endpoints so that is out of scope for this project.
