### ISSUE TITLE
obtain initial refresh token

### ISSUE THREAD

**Issue by rantanlan** [arpanghosh8453/public-fitbit-projects#15]
Hey, I would love to try your idea since the data you get in the app is crap.

Unfortunately, I'm no coder, but I know my way around docker and Linux, but I'm unable to get the initial token part. Do I need to grab that token programmatic somehow? Also do i need to expose this to the web for the oauth process? Didn't specify any valid redirect URL. Thanks for any information...

**Comment by arpanghosh8453** [comment]
You should create a new application here : https://dev.fitbit.com/apps/new

Follow the fields below and set a localhost address ( where no service is running ) as your redirect url. 

![image](https://github.com/arpanghosh8453/public-fitbit-projects/assets/26424944/8edf2f0d-42c4-43b9-b012-01a967d7a5ac)

After you fill out the form, you will get the client ID and client Secret. 

Go to this link and read the instructions carefully : https://dev.fitbit.com/build/reference/web-api/troubleshooting-guide/oauth2-tutorial/

Application Type should ber `Server`

After you click on the link here, it will redirect you to the invalid localhost address but the url in the address bar will have the required codes and parameters. You need to copy the whole url and paste in the red marked box below and you will be able to proceed. 

![image](https://github.com/arpanghosh8453/public-fitbit-projects/assets/26424944/c1de1819-0011-4a24-a7f3-afd03dc04f5b)

Once you get to the final stage, you should see a access and refresh token pair in the final fox here ( after clicking submit request ). You need to copy this final **valid** refresh token. 

Let me know if you are still having trouble. Then I can guide you personally. Thank you. I am closing this issue for now.
