### ISSUE TITLE
Option to change USER ID and GROUP ID ?

### ISSUE THREAD

**Issue by nodecentral** [arpanghosh8453/public-fitbit-projects#17]
Hi

In the docker compose instructions, the user and group IDs often causes me issues when it comes to using mapped folders on the host. For a while now, I always create them using user UID 1005 and GID 1000. Is it possible for a change of UID/GID to be supported ?

````
      - ./logs:/app/logs # logs folder should exist and owned by user id 1000
      - ./tokens:/app/tokens # tokens folder should exist and owned by user id 1000
````

**Comment by AskAlice** [comment]
I concur, possibly     `user: "${UID}:${GID}"` on every container, or alternately `user: "${PUID}:${PGID}"` with a supplemental .env file

**Comment by arpanghosh8453** [comment]
I am aware that [linuxserver](https://linuxserver.io/) provides the settings as part of compose file, but doing that is not very straightforward. The script (or the container) runs as a non-root user (appuser) if you are concerned about security implications 

```dockerfile
RUN groupadd --gid 1000 appuser && useradd --uid 1000 --gid appuser --shell /bin/bash --create-home appuser && chown -R appuser:appuser /app
USER appuser
```
You can always use `user: "${UID}:${GID}"` in any compose file if you want to do what you want. So I am closing this issue in favor to that.

**Comment by nodecentral** [comment]
Thanks @arpanghosh8453 / @AskAlice 

On a stackoverflow post some had suggested..

````
The docker run command can be passed a user and group (or uid / gid).

docker run --user 2000:2000 acme

Or, via compose, the user: attribute can be used.

compose.yml

services:
  acme:
    image: my-alpine:latest
    user: 2000:2000

In the case that ids are used, neither the user id or group id needs to exist in the container.
````

Is that a valid route too ?
