### ISSUE TITLE
Request: Inclusion of missing metrics

### ISSUE THREAD

**Issue by andersonsamalex** [arpanghosh8453/public-fitbit-projects#20]
Firstly, amazing job on this! I've searched high and low, and attempted far shoddier code to get this to work, and this worked out of the box.

Would it be possible to add the following metrics to be fetched, as they appear to be missing from the python script: [https://dev.fitbit.com/build/reference/web-api/body-timeseries/](url)

**Comment by arpanghosh8453** [comment]
Thank you for your kind words! 

I looked into it and I only find the weight part of the supported resources interesting (as that is raw data, and bmi etc are post-calculated from it). Although it needs to be manually entered, so many people might not have it, it is quite useful to see the trend for who does keep the track. I am considering adding the weight endpoint if that fits your needs. 

For this, I have another service (which is hosted online for public use https://fitbit-report.arpan.app/ ) on GitHub for report generation which supports weight data visualization. You can find it here : https://github.com/arpanghosh8453/fitbit-web-ui-app and let me know if that satisfies your needs already. 

Thanks again. Have a good day!
