### ISSUE TITLE
Feature Suggestion and Code

### ISSUE THREAD

**Issue by Jasonthefirst** [arpanghosh8453/public-fitbit-projects#24]
Hi, 

Again thanks for your awesome project. Because I wanted a quick way to integrate this into Home Assistant I changed your project into a Home Assistant Addon. 
Because I don't have much time currently I hacked it together and pushed it to my gitlab: [My Repo](https://gitlab.fristerspace.de/demian/fitbit-ha-addon). But if you want you can use it here in your project and I remove my repository again. 

In a few month I might have enough time for a regular pull request.

**Comment by Jasonthefirst** [comment]
@arpanghosh8453 Thanks for replying and being open :-). 
I revised the readme and docs.md (for the addon section in HA) and I will maintain the addon for the foreseeable future. 
I linked to your project and mentioned you so that people see these projects are connected. 
So if you want, you can link to my project and it is probably easier to maintain the addon seperately.

**Comment by arpanghosh8453** [comment]
Done! Thanks again. I have borrowed the features section from your readme as that looked pretty cool. Thanks again for using my project and developing this addon :)

**Comment by adamcodes716** [comment]
FYI - I appreciate the link to the add-on, but it isn't operational in HACS.   Fitbit won't allow me to download using the repo link, and when I put it into the folder manually, the server gave me a warning.  Also, "Settings" won't open after I added it.
