### ISSUE TITLE
[Request] Food statistics

### ISSUE THREAD

**Issue by skybarberom** [arpanghosh8453/public-fitbit-projects#26]
Would it be possible to integrate also food statistics? 
I have my food diary in the application and would be nice to see intake calories with macronutrients (Carb/Fat/Protein) to compare the days and the different intake.
Also adding weight and fat mass would be nice.

**Comment by arpanghosh8453** [comment]
Here are the available API endpoints from the Fitbit official documentation : https://dev.fitbit.com/build/reference/web-api/nutrition/

Here is a web interface for testing their output structure (please check #28 on how to run this) : https://dev.fitbit.com/build/reference/web-api/explore/#/Nutrition

I personally do not have any food log, so can't test out the cases in the endpoints. So I would like to have someone make a pull request on this if they are interested based on the above hints.
