### ISSUE TITLE
Device Battery Level

### ISSUE THREAD

**Issue by skybarberom** [arpanghosh8453/public-fitbit-projects#28]
Device Battery Level hasn't any data on my Sense2. Not sure if it's a general problem or model related.

**Comment by arpanghosh8453** [comment]
Hello @skybarberom,

Please test the `/1/user/-/devices.json` endpoint from here : https://dev.fitbit.com/build/reference/web-api/explore/#/

Steps to follow - 

- You must authorize the session first using the `Authorize` button 

![image](https://github.com/user-attachments/assets/48c2f5c5-1125-41f9-aae2-2a38f02faba4)

- Then run the abovementioned endpoint (use the `try it out` button and look for the following matrices

![image](https://github.com/user-attachments/assets/fe66425d-ada1-4a92-991a-af20e8610d35)

**Comment by skybarberom** [comment]
I tried to make tha call. That is what I get

<img width="1093" alt="image" src="https://github.com/user-attachments/assets/e7a61d64-c724-4616-bcd4-ab041d83b317">

**Comment by arpanghosh8453** [comment]
Awesome! Thanks for the update. 

You are right about the deduction, here is the function that gets the device battery level :

```python
def get_battery_level():
    device = request_data_from_fitbit("https://api.fitbit.com/1/user/-/devices.json")[0]
    if device != None:
        collected_records.append({
            "measurement": "DeviceBatteryLevel",
            "time": LOCAL_TIMEZONE.localize(datetime.fromisoformat(device['lastSyncTime'])).astimezone(pytz.utc).isoformat(),
            "fields": {
                "value": float(device['batteryLevel'])
            }
        })
        logging.info("Recorded battery level for " + DEVICENAME)
    else:
        logging.error("Recording battery level failed : " + DEVICENAME)

```

You can see the picked device is defined as the first item of the returned JSON -`request_data_from_fitbit("https://api.fitbit.com/1/user/-/devices.json")[0]` 

Closing this issue (as resolved) since you have already found a working solution.
