### ISSUE TITLE
KeyError: 'activityName'

### ISSUE THREAD

**Issue by tiomny** [arpanghosh8453/public-fitbit-projects#29]
I've been using Fitbit since 2013, and it seems that not all such old activity records have name.
So, the script fails snd exits
```
DEBUG - Requesting data from fitbit via Url : https://api.fitbit.com/1/user/-/activities/list.json
Traceback (most recent call last):
  File "/app/Fitbit_Fetch.py", line 742, in <module>
    fetch_latest_activities(end_date_str) # 1 query
  File "/app/Fitbit_Fetch.py", line 718, in fetch_latest_activities
    "ActivityName": activity['activityName']
KeyError: 'activityName'
 Live
```
I'm using HA addon, so the line number in log doesn't correspond to one in this repo.

**Comment by arpanghosh8453** [comment]
Yeah, it seems to be the case. You can verify if that's the case from the swagger web API endpoint `/1/user/-/activities/list.json` under the [activity section](https://dev.fitbit.com/build/reference/web-api/explore/#/Activity). Note that you need to click the green authorize button on the top first to authorize the page via Fitbit login, followed by clicking the `Try it out` button. For the values you should use 'desc' for sort and 50 for the limit. Set the offset to 0 and the beforeDate variable there as today when you run the query. This should give you the JSON. look if any of the entry item is missing the `activityName` parameter. 

As a quick fix, you can update the underlying python code inside the HA addon (plugin).

**Remove this first -**

```python
collected_records.append({
    "measurement": "Activity Records",
    "time": utc_time,
    "tags": {
        "ActivityName": activity['activityName']
    },
    "fields": fields
})
```
**Replace it with the following -**

```python
try:
    extracted_activity_name = activity['activityName']
except KeyError as MissingKeyError:
    extracted_activity_name = "Unknown-Activity"
  
collected_records.append({
    "measurement": "Activity Records",
    "time": utc_time,
    "tags": {
        "ActivityName": extracted_activity_name
    },
    "fields": fields
})
```

**Comment by tiomny** [comment]
I switched to docker instance, now I'm having this error 
```
2024-12-06 07:06:40,521 - DEBUG - https://api.fitbit.com:443 "GET /1/user/-/activities/heart/date/2024-12-05/2024-12-06.json HTTP/11" 200 None

Traceback (most recent call last):

  File "/app/Fitbit_Fetch.py", line 585, in <module>

    get_daily_data_limit_365d(start_date_str, end_date_str) # 8 queries

  File "/app/Fitbit_Fetch.py", line 492, in get_daily_data_limit_365d

    "Normal" : data["value"]["heartRateZones"][0]["minutes"],

KeyError: 'minutes'
```

**Comment by tiomny** [comment]
I use Fitbit One, it doesn't measure heart rate.

**Comment by arpanghosh8453** [comment]
> I use Fitbit One, it doesn't measure heart rate.

Hello @tiomny, This project unfortunately do not support Fitbit One devices without required modifications for additional error handlings associated with the missing endpoints in the python code.

**Comment by tiomny** [comment]
Is it possible to write wrapper for endpoints and sending values from response to DB that could verify missing values and handle missing endpoint errors?

**Comment by tiomny** [comment]
I'm not good in Python, I'm more C# developer.
I think there are lots of Python client libraries for Fitbit API, either you can generate it by yourself. Why don't you go that way?

**Comment by arpanghosh8453** [comment]
Yeah, but it was more of a personal learning project that I made open source.
