### ISSUE TITLE
Initial setup failure

### ISSUE THREAD

**Issue by skynet2mainframe** [arpanghosh8453/public-fitbit-projects#30]
File "/app/Fitbit_Fetch.py", line 582, in <module>
    get_intraday_data_limit_1d(date_str, [('heart','HeartRate_Intraday','1sec'),('steps','Steps_Intraday','1min')]) # 2 queries x number of dates ( default 2)
  File "/app/Fitbit_Fetch.py", line 261, in get_intraday_data_limit_1d
    data = request_data_from_fitbit('https://api.fitbit.com/1/user/-/activities/' + measurement[0] + '/date/' + date_str + '/1d/' + measurement[2] + '.json')["activities-" + measurement[0] + "-intraday"]['dataset']
KeyError: 'activities-heart-intraday'

any time i reload the container it fails to start correctly and this is the only fault.

**Comment by arpanghosh8453** [comment]
Please look into #23 and #7 

The setup issue related to that has already been addressed. If that does not solve your problem, please feel free to reopen that issue with the details.

**Comment by skynet2mainframe** [comment]
Hi, 

My bad id did it a couple of times and must have forgot on the lat attempt. Great work btw.
