### ISSUE TITLE
[Request] Support for InfluxDB 2.x, Docker Deployment, and Google Health Integration

### ISSUE THREAD

**Issue by mschabhuettl** [arpanghosh8453/public-fitbit-projects#5]
### Description:

Firstly, kudos on the excellent project. It's a great resource for tracking Fitbit metrics. However, I believe it could be further improved by considering the following enhancements:

#### Enhancement 1: Support for InfluxDB 2.x

InfluxDB 2.x offers improved performance and new features like the Flux query language. Adding support for this latest version would future-proof the project and could possibly make data fetching and storage more efficient.

#### Enhancement 2: Docker Deployment

Providing a Docker image would simplify the deployment process considerably. This would be a great help for users who prefer a plug-and-play solution without the hassle of managing dependencies.

#### Enhancement 3: Google Health Integration

It would be fantastic to expand the script's capabilities to fetch data from Google Health. This could make the project a comprehensive health metrics dashboard, incorporating data from multiple platforms.

### Motivation:

1. **InfluxDB 2.x Support**: To keep the project current and tap into the advanced features of the latest InfluxDB version.
   
2. **Docker Deployment**: To offer an easy and fast way to get the system running, ideal for users who may not be technically inclined.

3. **Google Health Integration**: To make this a one-stop solution for all personal health metrics, increasing its utility and appeal.

### Additional Context:

Integrating these features will likely necessitate code changes and possibly additional dependencies. However, their inclusion would significantly expand the project's functionality and user-friendliness.

I'm keen to hear the community's thoughts on these proposed enhancements. Thank you!

**Comment by arpanghosh8453** [comment]
Influxdb 2.x : The query language is clunky in 2.x, and here we are using the influxdb just for the database, not the whole package it brings with 2.x ( will cause overhead ). Please provide specific reasons why you would like to use 2.x ( The reason you provided is very generic and adds no valuable reason )

Docker Deployment: @jtbrush56 already contributed to this. https://github.com/arpanghosh8453/public-fitbit-projects/pull/2

Google Health Integration: This project is for Fitbit owners only. Fitbit API provides more data than synced google fit database.

**Comment by mschabhuettl** [comment]
My primary interest in InfluxDB 2.x support is due to its interoperability. I already have an InfluxDB 2.x server operational for other projects, and being able to consolidate all my data onto that version would simplify management. Given that InfluxDB 1.8 is increasingly viewed as legacy, aligning this project with the newer version could provide long-term benefits for users in similar situations.

**Comment by arpanghosh8453** [comment]
I personally do not see any scope where influxdb 1.8 is limiting this project. Influxdb 2.x has multiple issues with grafana integration and often hits compatibility issues. Hence, I would rather stay on their "legacy" version, which properly works and stable with grafana integration, given that I am not missing any critical feature that is useful for this project.

I have tried doing this project with influxdb 2.x and failed, if you think this can make that work, please make a pull request with suggested changes.

**Comment by arpanghosh8453** [comment]
@mschabhuettl Influxdb 2.x support is now available. You can try out the docker image if you want to. But I suggest avoiding flux and influxdb 2.x because flux support will be removed from influxdb 3.x
